import { ITask } from '../../@types/task';

// ----------------------------------------------------------------------

export const _taskList: ITask[] = [
  {
    id: '1',
    staffName: 'John Smith',
    staffId: 1,
    taskName: 'Prepare Daily Specials Menu',
    taskDescription: 'Create and finalize the daily specials menu for tonight\'s service',
    status: 'in-progress',
    priority: 'high',
    createdAt: '2025-01-01T08:00:00',
    updatedAt: '2025-01-01T10:30:00',
    isArchived: false,
  },
  {
    id: '2',
    staffName: 'Maria Garcia',
    taskName: 'Inventory Check - Walk-in Cooler',
    taskDescription: 'Complete full inventory check of walk-in cooler and update system',
    status: 'pending',
    priority: 'medium',
    createdAt: '2025-01-01T07:00:00',
    updatedAt: '2025-01-01T07:00:00',
    isArchived: false,
  },
  {
    id: '3',
    staffName: 'David Lee',
    taskName: 'Staff Training - New POS System',
    taskDescription: 'Train evening shift staff on the new point-of-sale system features',
    status: 'completed',
    priority: 'urgent',
    createdAt: '2024-12-31T09:00:00',
    updatedAt: '2024-12-31T14:30:00',
    isArchived: false,
  },
  {
    id: '4',
    staffName: 'Sarah Johnson',
    taskName: 'Clean and Organize Dry Storage',
    taskDescription: 'Deep clean dry storage area and reorganize shelving units',
    status: 'pending',
    priority: 'low',
    createdAt: '2025-01-01T06:30:00',
    updatedAt: '2025-01-01T06:30:00',
    isArchived: false,
  },
  {
    id: '5',
    staffName: 'Michael Chen',
    taskName: 'Review Wine Pairing Menu',
    taskDescription: 'Update wine pairing recommendations for new seasonal menu items',
    status: 'in-progress',
    priority: 'medium',
    createdAt: '2025-01-01T08:15:00',
    updatedAt: '2025-01-01T11:00:00',
    isArchived: false,
  },
  {
    id: '6',
    staffName: 'Emily Rodriguez',
    taskName: 'Prep Mise en Place for Dinner Service',
    taskDescription: 'Complete all prep work for tonight\'s dinner service - vegetables, sauces, garnishes',
    status: 'in-progress',
    priority: 'urgent',
    createdAt: '2025-01-01T09:00:00',
    updatedAt: '2025-01-01T12:15:00',
    isArchived: false,
  },
  {
    id: '7',
    staffName: 'Robert Taylor',
    taskName: 'Equipment Maintenance Check',
    taskDescription: 'Perform routine maintenance check on all kitchen equipment',
    status: 'pending',
    priority: 'medium',
    createdAt: '2025-01-01T07:30:00',
    updatedAt: '2025-01-01T07:30:00',
    isArchived: false,
  },
  {
    id: '8',
    staffName: 'Lisa Anderson',
    taskName: 'Update Allergen Information',
    taskDescription: 'Review and update allergen information for all menu items in the system',
    status: 'completed',
    priority: 'high',
    createdAt: '2024-12-30T10:00:00',
    updatedAt: '2024-12-31T16:00:00',
    isArchived: false,
  },
  {
    id: '9',
    staffName: 'James Wilson',
    taskName: 'Order Specialty Ingredients',
    taskDescription: 'Place orders for specialty ingredients needed for weekend specials',
    status: 'pending',
    priority: 'high',
    createdAt: '2025-01-01T08:45:00',
    updatedAt: '2025-01-01T08:45:00',
    isArchived: false,
  },
  {
    id: '10',
    staffName: 'Jennifer Martinez',
    taskName: 'Catering Event Planning',
    taskDescription: 'Finalize menu and staffing for corporate catering event on Friday',
    status: 'in-progress',
    priority: 'urgent',
    createdAt: '2024-12-31T11:00:00',
    updatedAt: '2025-01-01T09:30:00',
    isArchived: false,
  },
  {
    id: '11',
    staffName: 'Thomas Brown',
    taskName: 'Health Inspection Preparation',
    taskDescription: 'Ensure all areas are compliant for upcoming health inspection',
    status: 'cancelled',
    priority: 'medium',
    createdAt: '2024-12-29T08:00:00',
    updatedAt: '2024-12-30T10:00:00',
    isArchived: true,
  },
  {
    id: '12',
    staffName: 'Patricia Davis',
    taskName: 'Train New Dishwasher',
    taskDescription: 'Complete orientation and training for new dishwasher hire',
    status: 'completed',
    priority: 'low',
    createdAt: '2024-12-28T09:00:00',
    updatedAt: '2024-12-29T15:00:00',
    isArchived: true,
  },
];

