import { IProcessAudit, IAccessLog } from '../../@types/tracking';

// ----------------------------------------------------------------------

export const _processAuditList: IProcessAudit[] = [
  {
    id: 1422,
    modelName: 'MenuTemplate',
    objectId: '25',
    objectRepr: 'fsfds',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Create',
    timestamp: '2026-01-01T14:41:31.928154Z',
    formattedChanges: 'No specific changes recorded',
    restaurantName: 'FabTechSol',
  },
  {
    id: 1421,
    modelName: 'EditorTemplate',
    objectId: '15',
    objectRepr: 'EditorTemplate object (15)',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Create',
    timestamp: '2026-01-01T14:34:34.135915Z',
    formattedChanges: 'No specific changes recorded',
    restaurantName: 'FabTechSol',
  },
  {
    id: 1329,
    modelName: 'Branch',
    objectId: '6',
    objectRepr: 'Celia Kulas - FabTechSol',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Create',
    timestamp: '2026-01-01T10:40:19.752794Z',
    formattedChanges: 'No specific changes recorded',
    restaurantName: 'FabTechSol',
  },
  {
    id: 1328,
    modelName: 'Branch',
    objectId: '5',
    objectRepr: 'Celia Kulas - FabTechSol',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Create',
    timestamp: '2026-01-01T10:32:29.029487Z',
    formattedChanges: 'No specific changes recorded',
    restaurantName: 'FabTechSol',
  },
  {
    id: 1286,
    modelName: 'Branch',
    objectId: '3',
    objectRepr: 'sialkot - FabTechSol',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Update',
    timestamp: '2026-01-01T09:46:42.594953Z',
    formattedChanges:
      'social_media: [] → [{"name":"whatsapp","url":"https://web.whatsapp.com/"},{"name":"instagram","url":"https://www.instagram.com/"}]',
    restaurantName: 'FabTechSol',
  },
  {
    id: 1105,
    modelName: 'Recipe_Process_Audit',
    objectId: '1897',
    objectRepr: 'Real_time_Variable_Comment: 78\nstep: Real-time Variable Comment 1user@fabtechsol.com',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Create',
    timestamp: '2026-01-01T07:34:14.591278Z',
    formattedChanges: 'No specific changes recorded',
    restaurantName: 'FabTechSol',
  },
  {
    id: 1104,
    modelName: 'Recipe_Process_Audit',
    objectId: '1896',
    objectRepr: 'Real_time_Variable_Comment: 79\nstep: Real-time Variable Comment 2user@fabtechsol.com',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Create',
    timestamp: '2026-01-01T07:34:14.588106Z',
    formattedChanges: 'No specific changes recorded',
    restaurantName: 'FabTechSol',
  },
  {
    id: 1103,
    modelName: 'Cooking_Deviation_Comment',
    objectId: 'NEW',
    objectRepr: 'Cooking Deviation Comment 1',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Permanent Delete',
    timestamp: '2026-01-01T07:34:14.585377Z',
    formattedChanges: 'No specific changes recorded',
    restaurantName: 'FabTechSol',
  },
  {
    id: 1102,
    modelName: 'Cooking_Deviation_Comment',
    objectId: 'NEW',
    objectRepr: 'Cooking Deviation Comment 2',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Permanent Delete',
    timestamp: '2026-01-01T07:34:14.580709Z',
    formattedChanges: 'No specific changes recorded',
    restaurantName: 'FabTechSol',
  },
  {
    id: 1101,
    modelName: 'Cooking_Deviation_Comment',
    objectId: 'NEW',
    objectRepr: 'Cooking Deviation Comment 3',
    changedByName: 'FabTechSol Team',
    userRole: 'Admin',
    userEmail: 'user@fabtechsol.com',
    actionDisplay: 'Permanent Delete',
    timestamp: '2026-01-01T07:34:14.576018Z',
    formattedChanges: 'No specific changes recorded',
    restaurantName: 'FabTechSol',
  },
];

export const _accessLogList: IAccessLog[] = [
  {
    id: 412,
    user: {
      fullName: 'Sohail Khan',
      email: 'vodip15453@hh7f.com',
      role: 'A',
    },
    ipAddress: '192.168.32.3',
    userAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
    timestamp: '2025-12-30T14:27:09.921510Z',
  },
  {
    id: 411,
    user: {
      fullName: 'FabTechSol Team',
      email: 'user@fabtechsol.com',
      role: 'A',
    },
    ipAddress: '172.30.0.3',
    userAgent: 'PostmanRuntime/7.49.1',
    timestamp: '2025-12-30T11:16:53.778172Z',
  },
  {
    id: 409,
    user: {
      fullName: 'FabTechSol Team',
      email: 'user@fabtechsol.com',
      role: 'A',
    },
    ipAddress: '172.30.0.3',
    userAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
    timestamp: '2025-12-30T09:36:43.484294Z',
  },
  {
    id: 407,
    user: {
      fullName: 'FabTechSol Team',
      email: 'user@fabtechsol.com',
      role: 'A',
    },
    ipAddress: '172.30.0.3',
    userAgent:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36',
    timestamp: '2025-12-30T09:17:43.446100Z',
  },
  {
    id: 405,
    user: {
      fullName: 'FabTechSol Team',
      email: 'user@fabtechsol.com',
      role: 'A',
    },
    ipAddress: '172.30.0.3',
    userAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
    timestamp: '2025-12-30T08:43:54.613488Z',
  },
];

