import { IWineInventory } from '../../@types/wineInventory';

// ----------------------------------------------------------------------

export const _wineInventoryList: IWineInventory[] = [
  {
    id: '1',
    wineName: 'Cabernet Sauvignon',
    producer: 'Silver Oak',
    vintage: 2019,
    country: 'USA',
    region: 'Napa Valley',
    wineType: 'Red',
    wineProfile: 'Dry – Ripe Fruits & Spices',
    description: 'Full-bodied red with oak influence',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
    tags: ['House Favorite', 'By the Glass'],
    inventory: {
      '187.5': 50,
      '750': 300,
      '1500': 100,
      '3000': 10,
    },
    totalStock: 410,
    stockStatus: 'LOW',
    minStockLevel: 100,
    maxStockLevel: 500,
    purchasePrice: 22.5,
    supplierName: 'Global Wine Distributors',
    location: 'Main Restaurant',
    locationId: 'loc_01',
    isDeleted: false,
    createdAt: '2025-01-01T08:00:00',
  },
  {
    id: '2',
    wineName: 'Chardonnay',
    producer: 'Domaine Laroche',
    vintage: 2020,
    country: 'France',
    region: 'Burgundy',
    wineType: 'White',
    wineProfile: 'Dry – Fruit Sauce & Vanilla',
    description: 'Crisp and elegant with buttery notes',
    imageUrl: 'https://images.unsplash.com/photo-1506377247727-4b5e32a8c5e6?w=400',
    tags: ['By the Glass', 'Popular'],
    inventory: {
      '375': 25,
      '750': 450,
      '1500': 50,
    },
    totalStock: 525,
    stockStatus: 'IN_STOCK',
    minStockLevel: 200,
    maxStockLevel: 600,
    purchasePrice: 18.75,
    supplierName: 'French Wine Imports',
    location: 'Main Restaurant',
    locationId: 'loc_01',
    isDeleted: false,
    createdAt: '2025-01-01T08:00:00',
  },
  {
    id: '3',
    wineName: 'Pinot Noir',
    producer: 'Burgundy Estate',
    vintage: 2018,
    country: 'France',
    region: 'Burgundy',
    wineType: 'Red',
    wineProfile: 'Dry – Tart Fruits & Flowers',
    description: 'Light and fruity with earthy undertones',
    imageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400',
    tags: ['Premium', 'Special Occasion'],
    inventory: {
      '750': 150,
      '1500': 30,
    },
    totalStock: 180,
    stockStatus: 'IN_STOCK',
    minStockLevel: 50,
    maxStockLevel: 250,
    purchasePrice: 35.0,
    supplierName: 'Premium Wine Co.',
    location: 'Wine Cellar',
    locationId: 'loc_02',
    isDeleted: false,
    createdAt: '2025-01-01T08:00:00',
  },
  {
    id: '4',
    wineName: 'Prosecco',
    producer: 'Veneto Winery',
    vintage: 2021,
    country: 'Italy',
    region: 'Veneto',
    wineType: 'Sparkling',
    wineProfile: 'Dry – Tart Fruits & Flowers',
    description: 'Fresh and bubbly, perfect for celebrations',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
    tags: ['By the Glass', 'Celebration'],
    inventory: {
      '187.5': 100,
      '750': 200,
    },
    totalStock: 300,
    stockStatus: 'IN_STOCK',
    minStockLevel: 150,
    maxStockLevel: 400,
    purchasePrice: 12.5,
    supplierName: 'Italian Wine Distributors',
    location: 'Main Restaurant',
    locationId: 'loc_01',
    isDeleted: false,
    createdAt: '2025-01-01T08:00:00',
  },
  {
    id: '5',
    wineName: 'Sauvignon Blanc',
    producer: 'Marlborough Estate',
    vintage: 2022,
    country: 'New Zealand',
    region: 'Marlborough',
    wineType: 'White',
    wineProfile: 'Dry – Vegetables & Herbs',
    description: 'Zesty and aromatic with citrus notes',
    tags: ['House Favorite'],
    inventory: {
      '750': 80,
    },
    totalStock: 80,
    stockStatus: 'LOW',
    minStockLevel: 100,
    maxStockLevel: 300,
    purchasePrice: 15.0,
    supplierName: 'Pacific Wine Imports',
    location: 'Main Restaurant',
    locationId: 'loc_01',
    isDeleted: false,
    createdAt: '2025-01-01T08:00:00',
  },
  {
    id: '6',
    wineName: 'Merlot',
    producer: 'Bordeaux Vineyards',
    vintage: 2019,
    country: 'France',
    region: 'Bordeaux',
    wineType: 'Red',
    wineProfile: 'Dry – Ripe Fruits & Spices',
    description: 'Smooth and velvety with dark fruit flavors',
    tags: ['Popular'],
    inventory: {},
    totalStock: 0,
    stockStatus: 'OUT',
    minStockLevel: 50,
    maxStockLevel: 200,
    purchasePrice: 20.0,
    supplierName: 'European Wine Distributors',
    location: 'Main Restaurant',
    locationId: 'loc_01',
    isDeleted: false,
    createdAt: '2025-01-01T08:00:00',
  },
  {
    id: '7',
    wineName: 'Rosé',
    producer: 'Provence Winery',
    vintage: 2022,
    country: 'France',
    region: 'Provence',
    wineType: 'Rosé',
    wineProfile: 'Dry – Tart Fruits & Flowers',
    description: 'Light and refreshing, perfect for summer',
    tags: ['By the Glass', 'Seasonal'],
    inventory: {
      '750': 250,
      '1500': 20,
    },
    totalStock: 270,
    stockStatus: 'IN_STOCK',
    minStockLevel: 100,
    maxStockLevel: 350,
    purchasePrice: 14.0,
    supplierName: 'French Wine Imports',
    location: 'Main Restaurant',
    locationId: 'loc_01',
    isDeleted: false,
    createdAt: '2025-01-01T08:00:00',
  },
  {
    id: '8',
    wineName: 'Riesling',
    producer: 'Mosel Valley',
    vintage: 2021,
    country: 'Germany',
    region: 'Mosel',
    wineType: 'White',
    wineProfile: 'Semi-Sweet – Candied Fruit & Flowers',
    description: 'Sweet and floral with honey notes',
    tags: ['Dessert Wine', 'Special Occasion'],
    inventory: {
      '375': 15,
      '750': 120,
    },
    totalStock: 135,
    stockStatus: 'IN_STOCK',
    minStockLevel: 50,
    maxStockLevel: 200,
    purchasePrice: 16.5,
    supplierName: 'German Wine Specialists',
    location: 'Wine Cellar',
    locationId: 'loc_02',
    isDeleted: false,
    createdAt: '2025-01-01T08:00:00',
  },
  {
    id: '9',
    wineName: 'Malbec',
    producer: 'Mendoza Estates',
    vintage: 2020,
    country: 'Argentina',
    region: 'Mendoza',
    wineType: 'Red',
    wineProfile: 'Dry – Ripe Fruits & Spices',
    description: 'Bold and robust with dark berry flavors',
    tags: ['House Favorite', 'Popular'],
    inventory: {
      '750': 180,
      '1500': 40,
    },
    totalStock: 220,
    stockStatus: 'IN_STOCK',
    minStockLevel: 100,
    maxStockLevel: 300,
    purchasePrice: 19.0,
    supplierName: 'South American Wines',
    location: 'Main Restaurant',
    locationId: 'loc_01',
    isDeleted: false,
    createdAt: '2025-01-01T08:00:00',
  },
  {
    id: '10',
    wineName: 'Champagne',
    producer: 'Dom Pérignon',
    vintage: 2015,
    country: 'France',
    region: 'Champagne',
    wineType: 'Sparkling',
    wineProfile: 'Dry – Tart Fruits & Flowers',
    description: 'Luxury sparkling wine for special occasions',
    tags: ['Premium', 'Special Occasion', 'Celebration'],
    inventory: {
      '750': 25,
      '1500': 5,
    },
    totalStock: 30,
    stockStatus: 'LOW',
    minStockLevel: 20,
    maxStockLevel: 50,
    purchasePrice: 150.0,
    supplierName: 'Premium Wine Co.',
    location: 'Wine Cellar',
    locationId: 'loc_02',
    isDeleted: true,
    createdAt: '2025-01-01T08:00:00',
  },
];

